[package]
name = "ha-crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
rss = "2.0"
urlencoding = "2.1"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }